### ISSUE TITLE
建议将卡片类消息也纳入学习屏蔽

### ISSUE THREAD

**Issue by NtskwK** [InvoluteHell/Pallas-Bot#11]
不知道为什么，Pallas就学习到```卡片链接```信息了。因为```卡片链接```是不可以被```回复```的，所以也没有办法禁止它发送这个内容。
~~暂时只能提醒群友不要触发这个回复~~
![-4a0f0f5e7c28902a](https://user-images.githubusercontent.com/88552976/161109698-39c97356-9b15-4132-aa32-f2e12a90c877.png)

**Comment by MistEO** [comment]
等我有空来整下_(:з」∠)_

临时可以手动改下 MongoDB 的 `blacklist` 这个表，把这条消息加入进去然后重启 bot

**Comment by MistEO** [comment]
现在可以通过直接 `@牛牛 不可以` 的方式（直接发消息，不是回复）来拉黑最后一次发送的内容啦

**Comment by MistEO** [comment]
现在 ban 最后一句话的方式是 `@牛牛 不可以发这个`
