### ISSUE TITLE
主动发言功能增加禁止选项

### ISSUE THREAD

**Issue by zzyyyl** [InvoluteHell/Pallas-Bot#12]
牛牛的主动发言有时候会不明所以，希望这种时候能够回复“不可以”避免以后再次用同样的消息主动发言

**Comment by NtskwK** [comment]
也许你可以通过尝试把主动发言的阈值调高以达到预期的目的。我现在已经把这个值拉到200了(ㅇㅅㅇ❀)
它在
>Pallas-Bot/src/plugins/repeater/model.py
的第89行。
而这个值的具体作用在285行

**Comment by zzyyyl** [comment]
啊，其实我的意思是在`speak()`里的`message`应该增加一个`answer['keywords'] not in ban_keywords`的filter（这里`ban_keywords`的定义应该与`_context_find`的类似），在`model.py`的319-322行。
没理解错的话，**原来的代码应该会导致主动发言的时候可能说出被ban的消息**，这应该是个bug？

（刚提这个issue的时候还没仔细了解代码，是在使用过程中发现的）
