### ISSUE TITLE
轮盘赌默认就踢人，风险过高~

### ISSUE THREAD

**Issue by FengTuKuangZi** [InvoluteHell/Pallas-Bot#16]
建议首次默认启动时是禁言的轮盘。然后为什么是群主才能切换模式，管理员切换就失效呢？

**Comment by MistEO** [comment]
最一开始的设计压根没有打算做禁言模式，是仅踢人的。~~不想玩可以不玩~~ 在群友建议才加了禁言模式。如果有需要可以自己改改~
