### ISSUE TITLE
轮盘伪随机数 bug

### ISSUE THREAD

**Issue by MistEO** [InvoluteHell/Pallas-Bot#25]
https://github.com/InvoluteHell/Pallas-Bot/blob/43a40a1ad16965eafa7e0590cf4bfa11f5e34f98/src/plugins/roulette/pseudorandom.py#L22

从群友玩的结果来看，在玩了一定的次数之后，一枪死的概率非常高，在多个不同的群里多次遇到了。看了下伪随机的这部分代码，这里对 1 的处理是不是有问题？

**Comment by MistEO** [comment]
@LYZhelloworld

**Comment by MistEO** [comment]
补充描述一下，不是幸存者偏差的那种体感一枪死的概率很高，而是，连续五六次甚至更多次都是一枪死。接着恢复正常，随机到几的都有，继续玩了一段时间后，又出现连续五六次甚至更多次都是一枪死。只有 1 这个数字存在这种情况，其他数字没有出现过

**Comment by LYZhelloworld** [comment]
连续出现1的情况还是挺容易出现的，并且容易在心理上留下印象。相比之下越大的数连续出现给人的印象更浅。

如果觉得概率有问题可以模拟跑很多次看概率分布。

> https://github.com/InvoluteHell/Pallas-Bot/blob/43a40a1ad16965eafa7e0590cf4bfa11f5e34f98/src/plugins/roulette/pseudorandom.py#L22
> 
> 从群友玩的结果来看，在玩了一定的次数之后，一枪死的概率非常高，在多个不同的群里多次遇到了。看了下伪随机的这部分代码，这里对 1 的处理是不是有问题？

这部分没问题，只是把1到6转换成0开始的下标而已。
